### ISSUE TITLE
最新的xhttp能搞吗？

### ISSUE THREAD

**Issue by c21xdx** [BanKnight/nvless#1]
你好，xray最新出了xhttp，可以部署在一些限制websocket的项目中。有没有可能做一个类似这个项目的vless+xhttp呢？

**Comment by BanKnight** [comment]
> 你好，xray最新出了xhttp，可以部署在一些限制websocket的项目中。有没有可能做一个类似这个项目的vless+xhttp呢？

嗯？也行，我有空的时候看看是怎么操作吧。
